klarna/ui

package.json, webpack.config.js
This is to make the Dropdowns behave as they should, which are in the final products but not in the Showroom (whole area clickable).
=> Add autoprefixer to the Showroom 🎪

decorators/uncontrolled.jsx
This is **Part 1** of the saga of moving towards [controlled vs uncontrolled](https://github.com/klarna/ui/issues/45) being a consequence of the provided props instead of a feature of the component. This HOC allows for converting a fully controlled set of props in component into pseudo controlled. The typical case would look like this:
```js
import Field from '@klarna/ui/Field'
import uncontrolled from '@klarna/ui/decorators/uncontrolled'
export default uncontrolled(Field, {
prop: 'value',
defaultProp: 'defaulValue',
handler: 'onChange'
})
```
It will also work for making focus pseudo controlled like:
```js
import Field from '@klarna/ui/Field'
export default uncontrolled(Field, {
prop: 'focus',
defaultProp: 'autoFocus',
handler: 'onFocus',
reset: 'onBlur'
})
```
Merging this is completely …
=> Add HOC to make anything Uncontrolled on demand

Field/styles.scss, Input/styles.scss
In order for us to start using the native placeholder as a compliment to the label, it needs to be styled to look like the label.
=> Style input placeholder

Radio/example.jsx, Radio/index.jsx, Radio/styles.scss, css/settings.scss
This PR does two changes:
- Removes the hover state that would highlight the backgroud as gray;
- Add a new option `borderfull` to add borders between options.
=> Radio button tweaks

Switch/Toggle/index.jsx, Switch/Toggle/styles.scss
The code isn't the most beautiful thing I've ever written, but it works quite well. Feels A LOT better now than it did before.
The current implementation allows you to start swiping anywhere on the label or the bullet, because the bullet by itself is a rather small target.
Something to consider:
* We had an off-by-one error where you could swipe it 1px "too far", and then it would snap back to the right edge when you let go. I actually felt like this felt really good and tactile, but I'm not sure if that's the direction we want to go with these components.
=> Swipable switch

package.json
Otherwise we might bundle two distinct versions of React due to the way npm installs dependencies.
=> React and ReactMotion should be peerDependencies

Button/Primary/index.jsx, Button/Secondary/index.jsx, Button/Tertiary/index.jsx, Checklist/index.jsx, Dropdown/index.jsx, Field/index.jsx, IconButton/Back/index.jsx, IconButton/Close/index.jsx, IconButton/Hamburger/index.jsx, IconButton/Options/index.jsx, IconButton/Search/index.jsx, Installments/index.jsx, Link/index.jsx, List/Item/index.jsx, Paragraph/Primary/index.jsx, Paragraph/Secondary/index.jsx, Subtitle/index.jsx, Switch/Checkbox/index.jsx, Switch/Toggle/index.jsx, Title/Primary/index.jsx, Title/Secondary/index.jsx, decorators/overridable.jsx, decorators/themeable.jsx
In order for us to be able to override certain components' styles, or even override the entire component, we need to introduce a new `overridable` decorator. It does assume a couple of things, namely that a `design` object with a `getOverrideFor` method exists in the context.
The `getOverrideFor` method is expected to take a component and return an object with `css` and `Component`, where the `css` property is a CSS modules object and the `Component` is a React component.
This will be a breaking change if there are people using the `themeable` decorator directly in their projects.
Also, I only added it to the currently themeable components.
=> Make components overridable

Installments/styles.scss, package.json
Disable mouse interactions with the cell highlight element. The absolutely positioned highlight cell is preventing mouse interaction with the label element which is below it.
=> Disable installments cell highlight evens

templates/chromes/Centered/index.jsx, templates/examples/Informative.jsx
We need this to avoid clicking the button twice (clicking the button performs an HTTP POST in the authentication UI).
=> Add loading-state for the landing page

Field/PinCode/index.jsx, Field/PinCode/styles.scss, Field/example.jsx, css/settings.scss, templates/CodePrompt/index.jsx
=> Add placeholder and error styles for PinCode

templates/CodePrompt/index.jsx, templates/CodePrompt/styles.scss, templates/chromes/Centered/index.jsx, templates/chromes/Centered/styles.scss, templates/examples/Informative.jsx
Clicking the button may mean performing some async action, that may fail. We need to show this failure for the authentication service.
I just plain out copy-pasted the implementation of CodePrompt for this. Looks like this:
One thing that I noticed in the CodePrompt, is that the text doesn't wrap the way it was intended:
Current implementation:
vs the design:
Any ideas on how we could do this? I'll start playing around with it, but holla at me if you have a quick fix.
=> Add support for error message in the Centered chrome component

templates/CodePrompt/index.jsx, templates/CodePrompt/styles.scss, templates/examples/Prompts.jsx
We need to support the loading state of the CodePrompt template, but without any text next to the spinner. As a POC we sent in a space character `' '` which kind of worked, but it will still offset the spinner by 9px since the styles assume that there will be text.
I thought of 2 options to support this, and I don't have a very strong opinion, I just went with nr 2:
1. Pass `loading=true` to indicate that you want the loading state, but there's no text-string to show
2. Pass `loading=''` to indicate that you want the loading state, but the text is the empty string, aka there's no text-string to show
If there's another, better alternative, or if you like another option better, we can go with that.
=> Support code-prompt loading state without text

templates/CodePrompt/index.jsx
It wasn't actually using the variable `x`, it would short-circuit to `false || '0'` and return true every time.
@xaviervia WHERE'S YOUR IVORY TOWER NOW? :)
=> Fix the isDigit function

templates/CodePrompt/index.jsx, templates/examples/Prompts.jsx
We have a use case in the Authentication UI to show an error message, but the input should not be in the error state. This was our take on how to accomplish that.
=> Separate error state from error message in CodePrompt

Field/PinCode/index.jsx
Some devices (iOS 10) will leave the keyboard open if the field is disabled while it has focus. Since `PinCode` is used as an auto-submitting field, this will always happen.
I had another version where the logic was a more verbose and explanatory, like:
```jsx
componentWillReceiveProps (nextProps) {
const inputExists = !!this._input
const hasFocus = this.state.focus
const willBeDisabled = nextProps.disabled && !this.props.disabled
if (inputExists && hasFocus && willBeDisabled) {
this._input.blur()
}
}
```
Not sure if it adds that much though. The code as it stands now, along with the git log message, should be enough to explain what's going on. I think.
=> Trigger blur when PinCode field is disabled

.travis.yml
Since Travis uses yarn by default, it's already installing dependencies. No need to do it twice
=> No double dependency install on Travis

.travis.yml
As a first step for #181, it should be simple enough to at least show how a PR is affecting the bundle size.
Given that Travis executes the prepublish step and builds the distributed version, this should work.
Hopefully we'll see something like this when this PR is built, though there's no built-index.js to compare to, so we'll just see the absolute size, I think. But once it's in place, it'll compare it to the target branch and show you the relative difference.
=> Track bundle size changes

Installments/index.jsx
If you select the 4th payment option on iphone 6 in landscape mode and then rotate the phone, the component will end up in a state like on the following image
The position of the highlight element is not recalculated.
This PR is adding handler on `orientationchange` which updates the position to the highlight element to 0, 0 and that will trigger recalculation.
=> Add handler for orientationchange to installments component

Paragraph/Primary/index.jsx, Paragraph/Secondary/index.jsx
When implementing #213 accidentally updated the customisation property controlling the color of text for Primary and Secondary Title. Reverting to the proper one.
@xaviervia, @Nevon
=> [Title: Primary Secondary]Use the correct customization property for text color

Text/isThemeable.js, Theme/example.jsx
`isThemeable` should return the actual themed or not style.
The actual `adapter` function was never called, so merchant styling was never applied.
This should fix it :) @xaviervia @Nevon
=> Fix to ensure custom styled is applied on Text components when conditionally themed

Installments/index.jsx
Depending on the position of the highlight element it can brake the layout when the orientation is changed (from landscape to portail on iphone6).
To fix this, we will hide the highlight element, then show it and position it in the next thick. This will allow to the browser to update the layout properly and we will position the element in the resulting layout.
Browsers trigger `orientationchange` whenever the height becomes bigger than the width and vice versa. This PR prevent triggering of the `orientationchange` handler on resize of the browser window on desktop. In that case the media queries should handle the layout change.
=> Hide and show the highlight element on orientation change

Installments/index.jsx
Do not track the current layout orientation, just trigger recalculation of the highlight position on `orientationchange`
=> Remove layout orientation tracking

List/Iconic/index.jsx, List/Iconic/styles.scss
Alignment of elements with smaller text than image are fixed now.
=> Update iconic lists

Collapsible/index.jsx
Overflow rule to enable content to overflow outside the collapsible once the animation is close to be complete (the last few pixels take a while to be expanded).
'10' is a magic number 🎩
=> Allow content to overflow on an expanded Collapsible

Radio/styles.scss
Logos should be grayed-out for the locked payment options.
=> KCOC-1407 - Logos should be "grayed-out"

Radio/index.jsx, Radio/styles.scss
This fixes an issue in IE10 that prevents interactive content inside the Radio to be changed (such as selection element).
=> Make the Radio option header the only clickable part

Radio/styles.scss, css/settings.scss
We have an issue with merchant styling overwriting the text color of locked methods. We can output the same look by using opacity and this will make merchant styling work properly. 
Current Look:
Look with Proposed Changes
Merchant Styling Look with Proposed Changes
=> Use opacity for disabled radio text

Collapsible/index.jsx
Since `updateHeight` can happen asynchronously (debounced), it might be executed after the component was already unmounted.
This issue should not have any usability issue, but we should be wary of it on any component that uses `debounce`.
=> Fix Collapsible's `null is not an object`

Radio/example.jsx, Radio/styles.scss
=> Fix spacings for Radio selector items

IconButton/Back/index.jsx, IconButton/Close/index.jsx, IconButton/Hamburger/index.jsx, IconButton/Options/index.jsx, IconButton/Search/index.jsx
The issue was that the `withDisplayName` higher-order component was applied too late, after the `overridable` already picked up a wrong `displayName` for the IconButtons. This was causing style overrides not to apply.
=> Make sure displayName is set in IconButtons when overridable

Installments/Horizontal/styles.scss, Installments/Vertical/styles.scss
The problem is that the highlight element on Android stock browser looked like a blue dot, like on the image below
To fix it, instead of calculating the width and the height of the highlight element using `calc()`, which is not supported in old Android stock browser, we will use workaround by setting the `top`, `bottom`, `left`, `right` to `-1px`.
For the horizontal installments we have to set the `height` explicitly to fix it for IE9 and IE10.
With the solution above in Android stock the `2px` compensation for the border doesn't work only for the horizontal component. But it looks acceptable and the solution works pixel perfect in all other browsers (checked in IE9, IE10, IE11, Firefox, Safari, Chrome)
Here is how it looks on Android stock now:
=> Fix installments heighlight dimensions on android stock

Collapsible/index.jsx, Collapsible/styles.scss, lib/debounce.js
The are two big changes is this PR to improve the overall performance:
- Moved away from React Motion to CSS Transitions;
- Only calculate the height of the content if it is not collapsed or it is about to be expanded.
A caveat from this change is the new animation:
=> Optimise Collapsible rendering

.babelrc, package.json
Having a .babelrc formatted for Babel 6 causes problems when running in a project using Babel 5.
Moving the content from .babelrc into package.json fixes the issue.
=> Move content from babelrc to package.json

.babelrc, package.json
This reverts #259. Unfortunately, it doesn't work, given Babel 5 still reads the contents of the `package.json` file in the dependencies.
A local project with Babel 5 has a postInstall "hack" that deletes all `.babelrc` files, making it work.
The real solution is to update this projects from Babel 5. But the bigger question is if we should publish the `.babelrc` to the npm registry at all.
=> Revert "Move content from babelrc to package.json"

Collapsible/index.jsx, Collapsible/styles.scss
- Once the Collapsible has completely expanded, we set the height to ‘auto’
- No longer we need to listen to window resize events!
- Put React Motion back (easier to implement and not really the biggest performance penalty anyway)
=> Fix collapsisble hiding content

Collapsible/index.jsx
The check in `componentWillReceiveProps` was incorrect, leading to calculations being performed on every prop change.
And since we can now have components that don’t have the height on first render, we need a check in the Motion height against the `collapsed` prop, otherwise the Collapsible would show expanded (not opacity) on first render.
=> Fix Collapsible calculating height all the time

.npmignore, browserslist
This is to fix #268
This will be a breaking change when merged since some consumers might be relying on the browserslist for their autoprefixer setup.
=> Remove browserlist from npm package

Button/example.jsx, IconButton/Select/index.jsx, IconButton/index.jsx, IconButton/styles.scss, Selector/Input/index.jsx, Selector/Input/styles.scss, Selector/example.jsx, Selector/index.jsx, Theme/example.jsx
This is a new component. Its purpose is to:
- Look and behave much like an `<Input>`, but without the editable "input" field
- Show that a value can be "selected", and
- Show the "selected" value if there is one.
The selection itself is _not_ connected to the component. Here's a concept where the fullscreen dialog transitions to a `Selector.Options` component to do the selection:
This has been pretty much a copy-paste from `<Input>`, which means that it has support for modes like `big`, `giant`, `icon` etc., it's stackable inside fieldsets, and so on. All variations haven't been confirmed or optimized, since it's not going to be needed right now. I left it in there anyway so it would be easy to fine-tune it when needed. It also supports dynamic/merchant/themeable styling, which is a …
=> Selector Input

Button/example.jsx, Button/styles.scss
Add support for __big__ brand volume buttons
=> Add example and increase border radius

Selector/Input/index.jsx, Selector/Options/index.jsx, Theme/example.jsx, icons/Checkmark.jsx
Makes the `Selector.Options` component themeable. Here it is in all its colorful glory:
And for reference, here's the default look:
=> Make Selector.Options themeable

Installments/index.jsx
The installments component in auto mode should change it orientation (vertical or horizontal) depending on the size of the screen. If we decrease the screen size to have the vertical installments active and we start to slowly increase the width, when we come closely to the width break point the layout of the component breaks and stays like that until we interact with it.
The broken layout is displayed all the time for devices with screen sizes in the "breaking range", or if we load the component in a dialog.
On some IE versions the component is broken because the window.innerWidth property is missing. That's why I fallback to document.body.clientWidth if it does not exist.
=> Fix the installments broken layout 

Selector/Input/index.jsx, Selector/Input/styles.scss, Selector/example.jsx
Fixes a few details in the disabled state of the SelectorInput component:
- Cursor should not be 'pointer'
- The link should be hidden
- The onClick handler should not fire when clicked
Regular vs disabled:
=> Fix disabled state of the SelectorInput component

Selector/Options/index.jsx
This is to make the themeable version of the component behave like the default version, as per #280
=> Remove the highlighted text on themeable selected option

.gitignore, Theme/example.jsx, lib/features/stacking/index.js
The existing implementation only concerned top-, bottom-, and square fields. This adds support for left- and right variations as well.
=> Calculate border-radii for all variations of stacked fields

MouseflowExclude/index.jsx
We're using MouseflowExclude in our project and started noticing these errors:
TypeError: undefined is not an object (evaluating 'span.childNodes[0].nodeType')
I believe this is because some unit tests will mount our components and not provide the props required to render the stuff that is supposed to be between the `<MouseflowExclude>` tags. Therefore there are no childNodes to the `span`, and it throws an error.
I think the component should handle this case, for testing-convenience, but also to avoid unnecessary runtime errors that may happen.
=> Fix empty mouseflow nodes

Collapsible/index.jsx
The current implementation leaves all Collapsibles as `overflow: visible` on mount. However it only manifest itself as an issue in IE11.
- Move around the documentation explaining the reasoning
- Add an extra rule that keeps the overflow hidden while collapsed
=> Fix Collapsible allowing content to overflow

templates/CenteredForm/index.jsx, templates/CenteredSelection/index.jsx, templates/CodePrompt/index.jsx, templates/ConfirmData/index.jsx, templates/Explanation/index.jsx, templates/FilteredSelection/index.jsx, templates/Selection/index.jsx, templates/SingleInputPrompt/index.jsx, templates/XStepExplanation/index.jsx, templates/chromes/Centered/index.jsx, templates/examples/Informative.jsx, templates/examples/Prompts.jsx, templates/examples/Selection.jsx
This PR adds `id` property support for all available templates. The behavior is that the provided `id` will be used as a prefix in the inner component, for example `${id}__title`. This is the same that was used for individual components.
=> Add ids to templates

IconButton/Back/index.jsx, IconButton/Close/index.jsx, IconButton/Hamburger/index.jsx, IconButton/Options/index.jsx, IconButton/Search/index.jsx, IconButton/Select/index.jsx, IconButton/styles.scss
Improves the IconButton on Android 4.x devices. Apparently, having `padding` on an `<svg>` causes a lot of problems on older Android devices. I found this by spending much of my sanity in the Android emulator, tweaking the various css properties for `IconButton`.
As a small bonus, the `:active` hint (the circle with the background color) now also works on IE 10/11, by adding `pointer-events` to the svg to let the click event fall-through to the divs behind it. However it still only works if you click the actual icon, not the text. I assume this has to do with how the `:active` pseudo selector is implemented. But, I think this is a minor improvement so I kept it.
=> Fix broken IconButton on android

Collapsible/index.jsx, Radio/ExpandLabel/index.js, Radio/ExpandLabel/styles.js, Radio/example.jsx, Radio/index.jsx, lib/toMoveToHoCs/withHoverStyles.js, lib/toMoveToHoCs/withTouchStyles.js, package.json, settings/fontFamilies.js, settings/fontSizes.js, settings/fontWeights.js, settings/grid.js, settings/palette.js, yarn.lock
Notes to the reviewer:
- This has been tested in IE 9, IE 10, iOS simulator, Safari Firefox and Chrome desktop. It would be ideal to give it a quick run in Android Stock browser, but other than that looks fairly promising.
- There are [two](https://github.com/klarna/ui/pull/296/files#diff-b5545cd74975f65dbd1829cc6ded71fc) [new](https://github.com/klarna/ui/pull/296/files#diff-a0b50c48a2153dd6bfce6f5b43e1d7eb) higher-order components added to deal with inline styles for the new ExpandLabel component (Radio only, which is why it doesn’t have a place in the showroom). These two higher-order components **should be moved to [@klarna/higher-order-components](https://github.com/klarna/higher-order-components)**—the reason they are not right now is that it can be done in the next release.
- The …
=> Partially collapsed Radio selector

Radio/example.jsx, Radio/index.jsx
- Better document the `fullyExpanded` prop;
- Don't render the expand label if the number of options can fit the `visibleOptions` configuration;
- Allow the Radio to be fully collapsed.
=> Improvements to Radio visible options

Radio/index.jsx
We saw this issue recently popping up in our Sentry logs.
It can happen if the prop in not correctly set. This change makes the component more defensive about the value of `this.props.focus`.
I've also extracted an `applyFocus` function to be shared by both `componentDidMount` and `componentDidUpdate` hooks.
The actual fix can be seen at 7d2525e.
=> Fix Cannot read property 'focus' of undefined

BoxSelector/index.jsx
The default BoxSelector component switches between the Horizontal and the Vertical component depending on the screen size. But since it was not overridable, even the nested components were overridable, the custom designs are not propagated properly.
I tested, it looks that only the `overridable` high-order component is needed, it works fine without `themeable` or `uncontrolled`.
=> Make the default BoxSelector overridable

Button/Primary/index.jsx, Button/Secondary/index.jsx, Button/Tertiary/index.jsx, Button/styles.scss
until now when a button move to 'loading' or 'success' mode we have to manually set his size to avoid a weird 'jump' in the ui..... no more!
tnx @omriyariv for the css solution
before:
after:
if you have better idea pls ping me
=> Button loading width

Button/Primary/index.jsx, Button/Secondary/index.jsx, Button/Tertiary/index.jsx, Button/example.jsx, css/mixins/button.scss
`Button` components (`Primary`, `Secondary` and `Tertiary`) now support the `href` and `target` props that will cause them to render as `<a>`.
Fixes https://github.com/klarna/ui/issues/321
=> Support link in button

BoxSelector/index.jsx, Radio/Option/index.js, Radio/Option/styles.js, Radio/example.js, Showroom/examples/compositions/UncontrolledForm.jsx, Showroom/examples/compositions/UniqueIds.jsx, Theme/example.jsx, lib/device.js
Removes `leftPad` toggle prop for adding/removing left padding in the `Radio` component, since it invites for inconsistency in the presentation of `Radio` content.
This will, depending on device screen size vary left & right padding between 4 or 9.8 grid multiplier.
Would be a good idea to create a Component listening to 'resize'/'onresize' events depending on browser, and populate these values to `context` for better handling in responsive contexts.
=> Remove leftpad in radio for mobile

Button/styles.scss, css/mixins/button.scss
Not the most graceful solution. Don't know how much I'll break. 
Gives an alternative approach to how badly buttons fail in a responsive context for multi-word labels.
We could perhaps build on this?
=> Slightly better fail for long button labels in responsive context

BoxSelector/Horizontal/index.jsx, BoxSelector/Vertical/index.jsx, Button/Primary/index.jsx, Button/Secondary/index.jsx, Button/Tertiary/index.jsx, Checklist/index.jsx, Dialog/index.jsx, Dropdown/index.jsx, Field/index.jsx, Link/index.jsx, List/Item/index.jsx, Paragraph/Primary/index.jsx, Paragraph/Secondary/index.jsx, Radio/index.js, RadioMark/index.js, Selector/Input/index.jsx, Selector/Options/index.jsx, Subtitle/index.jsx, Switch/Checkbox/index.jsx, Switch/Toggle/index.jsx, Title/Primary/index.jsx, Title/Secondary/index.jsx
From:
```javascript
themeable((customizations, { customize }) => ({
customize: {
...customize,
backgroundColor: customizations.color_button,
borderRadius: customizations.radius_border,
textColor: customizations.color_button_text
}
}))
```
To:
```javascript
themeable((customizations, { customize }) => ({
customize: {
backgroundColor: customizations.color_button,
borderRadius: customizations.radius_border,
textColor: customizations.color_button_text,
...customize
}
}))
```
=> Fix customize override order

Collapsible/index.js
If you tab through the options inside the `Radio` component, the options will become blank and noninteractive in Chrome. This seems to be caused by the layout change of the `Collapsible` component. The fix is to put `overflow: hidden` to it when collapsed. It's only an issue for the non-animated variant, as the animated already specifies `overflow`.
=> Add overflow to regular (non-animated) Collapsible component

BoxSelector/Vertical/styles.scss
On narrow devices the text inside the vertical BoxSelector content can get really close to the right border instead of wrapping onto a new line. This is because there is no right padding on the content element. The right padding should be the same as the left one in order for the text to wrap properly.
=> Use same padding on both left and right side of vertical BoxSelector content

Radio/Option/index.js
React conciliation script is mistakenly applying styles for options across different states for Radio/Option elements.
This patch will prevent it from happening.
=> Add key identifier for Radio/Option

webpack.config.build.js
This is to avoid bundling a separate copy of React in this build, which
causes problems like this:
https://facebook.github.io/react/warnings/refs-must-have-owner.html
With this change it is possible to load kui without changing the webpack.config.js of projects that wish to use this library, and avoid having to add dependencies like `node-sass` (which has its own host of problems with having to run `npm rebuild node-sass` time and again).
Wonderful UI library you are open sourcing btw 🎉
=> Add peer dependencies to externals

templates/SingleInputPrompt/index.jsx
This PR intends to solve the bug in issue #372 , according to the intended behavior the `onAccept` method passed as a prop to `SingleInputPrompt` should be invoked when enter is pressed while the focus is in `Input` component but it's not invoked. 
First PR :tada: 
The current tests are all passing. Tested this with `yarn:test` and `yarn:test-unit`. Verified this behavior successfully by running the current test examples for `SingleInputPrompt`
cc @OscarF
=> Accept SingleInputPrompt when enter is pressed

Dialog/styles.scss, Dropdown/styles.scss
Make dialog X-icon easier to click/touch in narrow layout and use default cursor on disabled dropdown.
=> "Fix" Dialog X-Icon in Narrow + Disabled Dropdown Cursor

Preview/example.jsx, Preview/index.jsx, Theme/example.jsx
My attempt at making the components inside the Preview component themeable/customizable.
I don't have access to the styleguide because I don't have Sketch on my laptop, which means that I might or might not be off on what styles to use where.
One thing I wasn't able to figure out was how to use the dynamic border-color only when Preview.Main is hovered. Right now the border-color is set as default and hovering Main doesn't do anything. If anyone has an idea of how to get that working, please let me know. Or, maybe border-color isn't actually necessary here(?)
Also, please let me know if it's expected that I add another Preview example that contain these customization options.
=> Make Preview themeable

Radio/Option/styles.js, Switch/Checkbox/styles.scss
https://github.com/ftlabs/fastclick/issues/60
This fix is just for the checkbox. I guess I should do the same for `Radio`
Is this the right way to do it? Or should I try to use styles in JavaScript?
=> fix for fastclick making labels not working properly in iOS WebViews

package.json, templates/chromes/Centered/index.jsx, templates/examples/Informative.jsx
To disable Accept button in case you don't want to show an internal Loader.
=> Add `acceptDisabled` to Landing template

TermsBanner/index.jsx, index.js, tests.js
I've tried using the pre-compiled version and noticed that the Selector wasn't exported properly. So I've added a simple test for checking that it doesn't happen again.
=> Selector not exported correctly

BoxSelector/Horizontal/index.jsx, BoxSelector/Vertical/index.jsx, Dropdown/index.jsx, Field/index.jsx, IconButton/Back/index.jsx, IconButton/Close/index.jsx, IconButton/Hamburger/index.jsx, IconButton/Options/index.jsx, IconButton/Search/index.jsx, IconButton/Select/index.jsx, Radio/index.js, Switch/Checkbox/index.jsx, Switch/Toggle/index.jsx
The current implementation of `withOverrideFromContext` relies on the `displayName` of its target to find the override props for it in the React context. This approach does not work when `withOverrideFromContext` is not the first HOC to wrap the target component in the function composition order. 
This patch changes the order of the composition to make `withOverrideFromContext` be the first HOC that wraps the UI components to mitigate the issue while `withOverrideFromContext` does not get patched.
Suggestion to make `withOverrideFromContext` more reliable: Wrap it in a closure that takes a `targetName` argument and uses it to get override props from the context.
=> Call 'withOverrideFromContext' last when composing HOCs

Dropdown/styles.scss
The `top` styling for the Dropdown causes it to be 1px out of position. This makes it look like there's a 2px border when stacked with other Field components.
With `top: ($grid * -.2);`
Without `top: ($grid * -.2);`
=> Remove unnecessary top offset

Checklist/index.jsx, Checklist/styles.scss
Fix the margins and paddings of the `Checklist` so that they are the same as before the title and footer were introduced. Also only render `li`s inside the `ul` in order to render valid HTML.
=> Fix checklist margins and paddings

css/mixins/tooltip.scss
=> Give tooltip z-index
