klarna/ui

List/Item/index.jsx, List/Item/styles.scss, List/Ordered/index.jsx, List/Ordered/styles.scss, List/Unordered/index.jsx, List/Unordered/styles.scss, List/styles.scss, Showroom/Grid/index.jsx, Showroom/Main/index.jsx, Showroom/states.js, Showroom/streams/arrows.js
=> Fix List.Unordered bullet styles

Showroom/Sidebar/styles.scss, Switch/Checkbox/index.jsx, Switch/Checkbox/styles.scss, Theme/example.jsx, themeable/Switch.jsx
=> Fix switch focus state

Button/example.jsx, IconButton/index.jsx, IconButton/styles.scss
=> Add option of having labels to IconButtons

Code/syntaxes/imports.js, Field/example.jsx, Field/index.jsx, Input/example.jsx, Input/index.jsx, package.json
=> Add support for input element override

MouseflowExclude/example.jsx, MouseflowExclude/index.jsx
I wasn't able to find an example of an exported HoC anywhere, so I just made up a pattern for it. Let me know if you think it should be structured some other way.
=> Add HoC for MouseflowExclude

Switch/Checkbox/styles.scss
=> Vertically align checkbox labels

Dialog/styles.scss
=> Position Dialog IconButton relative to Dialog

Checklist/styles.scss
=> Make checklist have grey background

Loader/index.jsx
Fixes #92.
It was surprisingly easy :D -> http://stackoverflow.com/a/26220870/5801727
=> Fix spinning Loader in Safari

Button/example.jsx
=> Improve IconButton examples in Showroom

IconButton/styles.scss
Enjoy @hannah-ahl @Deschtex #teamPixelVision
=> Update gray IconButton to use gray-text color 🌈

Theme/index.jsx
```javascript
import { DEFAULTS } from '@klarna/ui/Theme'
```
=> Add defaults to theme component

.travis.yml
=> Use node 6 in travis for better speed

Switch/Checkbox/index.jsx, Switch/Checkbox/styles.scss
=> Remove switch mode for checkbox

templates/FilteredSelection/index.jsx
=> Fix FilteredSelection summary color

decorators/uncontrolled.jsx, templates/CenteredForm/index.jsx, templates/CenteredForm/styles.scss, templates/chromes/Centered/index.jsx, templates/chromes/Centered/styles.scss, templates/examples/Prompts.jsx
=> Add form prompt template

templates/Explanation/index.jsx, templates/FilteredSelection/index.jsx, templates/FilteredSelection/styles.scss, templates/Selection/index.jsx, templates/Selection/styles.scss
=> Fix top margins in templates

Field/example.jsx, Input/example.jsx, lib/features/inlinedIcon/index.jsx
=> Add Bank icon for Field/Input

Fieldset/example.jsx, Fieldset/index.jsx
=> Dropdown support on fieldset

Installments/index.jsx, Installments/styles.scss, lib/debounce.js, lib/requestAnimationFrame.js
Mostly works in horizontal mode now. The borders don't re-appear at the
correct time. I think maybe I'll have to use animation instead of
transitions for those.
Haven't started working on vertical mode yet. It becomes a lot trickier,
since the vertical height is not the same for all the options.
Fixes #41
=> Animate installments

Installments/index.jsx, Installments/styles.scss
=> Manually handle hover state in Installments

Collapsible/index.jsx, Installments/styles.scss, README.md, Radio/example.jsx, Radio/index.jsx, Radio/styles.scss, Showroom/examples/compositions/UncontrolledForm.jsx, Theme/example.jsx, css/settings.scss, package.json
This PR normalizes how we do alignment inside the Radio options. 
- The checkbox itself is vertically aligned with the content
- The top and bottom margin are now consistent (which was a problem when `borderful` was selected)
Here is how it looks now in a wide range of use-cases:
=> Revamped radio selector

decorators/overridable.jsx
Set styles instance property properly also when component updates
=> Fix issue in overridable decorator

Field/index.jsx, Theme/example.jsx
=> Fix rounded borders on error field

Switch/Checkbox/index.jsx, Theme/example.jsx
=> Dynamic styled Switch respects error state color

templates/SingleInputPrompt/index.jsx, templates/examples/Prompts.jsx
This puts the loading spinner on the accept button and disables the input
field.
=> Add support for loading prop in SingleInputPrompt

Radio/index.jsx, Radio/styles.scss
* Fixes #202
* Closes #187
* Closes #191
=> Render disabled input when Radio is disabled

Radio/index.jsx
=> Revert "Include the for label for the radio, only when not disabled"

README.md, Showroom/Page/GettingStarted/index.jsx
=> Document peer dependencies

IconButton/Back/index.jsx, IconButton/Close/index.jsx, IconButton/Hamburger/index.jsx, IconButton/Options/index.jsx, IconButton/Search/index.jsx, IconButton/withDisplayName.js, decorators/namespacedDisplayName.jsx
=> Add displayName to IconButtons

Dialog/index.jsx
=> Have the Dialog respect the custom styled border-radius

Paragraph/Primary/index.jsx, Paragraph/Secondary/index.jsx, Subtitle/index.jsx, Text/index.jsx, Text/isThemeable.js, Title/Primary/index.jsx, Title/Secondary/index.jsx
=> Do not promote custom styling for Text elements, when the color prop is error or warning.

Installments/index.jsx, Installments/styles.scss
=> Fix the Installments component growing on iphone6 landscape

Button/Price/index.jsx, Checklist/index.jsx, Dropdown/index.jsx, Field/index.jsx, Input/index.jsx, List/Iconic/index.jsx, Strong/index.jsx, Tooltip/index.jsx
=> Spread props on top level or add id to all Components

Button/Primary/index.jsx, Button/Secondary/index.jsx, Button/example.jsx, Button/styles.scss, lib/brandVolumeLevels.js
=> Add high brand volume to Buttons and templates

templates/ConfirmData/index.jsx, templates/ConfirmData/styles.scss, templates/ReviewData/styles.scss, templates/SingleInputPrompt/index.jsx, templates/SingleInputPrompt/styles.scss, templates/chromes/Centered/index.jsx, templates/chromes/Centered/styles.scss
These are updates that we agreed together with the designers for improving several of the templates. We already reviewed the resulting design while pairing, so this PR only needs code review =)
=> Several template updates

Installments/index.jsx
It was not being applied to the cells.
=> Fix theme support for instalments border radius

Installments/Horizontal/index.jsx, Installments/Vertical/index.jsx, Menu/Segmented/index.jsx, Menu/Tab/index.jsx, Radio/example.jsx, Radio/index.jsx, Selector/Options/index.jsx, Showroom/examples/compositions/UncontrolledForm.jsx, Switch/Checkbox/index.jsx, Switch/Toggle/index.jsx, lib/features/programmaticFocus/index.js, lib/getActiveElement.js
Haven't actually tested this. Could someone who actually works in front–end and has a VM with IE9 make sure that it works?
=> Fix document.activeElement in IE9. Fixes #253

Radio/index.jsx, Radio/styles.scss
=> Change cursor on selected Radio

Dropdown/example.jsx, Dropdown/index.jsx, Dropdown/styles.scss
=> Vertically center dropdown if label is empty

Button/Primary/index.jsx, Button/Secondary/index.jsx, Button/example.jsx, Theme/example.jsx, Theme/index.jsx
=> Support brand volume buttons as theme configuration

Button/example.jsx, css/mixins/button.scss
=> Change brandVolume price button padding

Selector/Options/styles.scss
=> Remove blue highlight from Selector.Options when selected

css/mixins/button.scss
=> Only make 6 grid radius on big branded button

Switch/Checkbox/styles.scss
Added default box-sizing property so it does not break when border-box is used in a project
=> Added default box-sizing property 

Menu/Tab/index.jsx
=> Recalculate highlight on resize for Menu.Tab

Switch/Checkbox/index.jsx, Switch/Checkbox/styles.scss, Switch/example.jsx
=> Add partial prop to the checkbox component

Button/Tertiary/index.jsx, Button/example.jsx, Button/styles.scss
=> brand-volume-high to Button.Tertiary

ProgressBar/index.jsx
First mount of component had issues with percentage stuck at 100
=> Default percentage to 0

Dropdown/example.jsx, Field/example.jsx, Input/example.jsx
The `focus` prop was missing the `real` value. Thanks @MikaelAmborn
=> Fix code examples for 'real' focus

README.md
package.json:
```
"peerDependencies": {
"ramda": "^0.21.0",...
```
=> add ramda to install in readme.md

Collapsible/index.js
=> Fix Collapsible no animation minimum height

Dropdown/example.jsx, Dropdown/styles.scss
> Fix to https://github.com/klarna/ui/issues/172
=> Add ellipsis to content of super narrow Dropdown

List/Iconic/index.jsx, List/Iconic/styles.scss
- Minor alignment fix for when an Iconic List is wrapped in a centered context.
=> Alignment-fix for Iconic Lists in wrapped in centered context

Button/Secondary/index.jsx, Button/example.jsx
=> Fix borderRadius in Button.Secondary with dynamic styling

templates/Wrapper/index.jsx, templates/Wrapper/styles.scss
Even though this will be _super fixed_ in the future with flex.
=> Adds verticalCenter prop on Wrapper

Radio/Option/index.js, Radio/Option/styles.js, Radio/index.js, package.json, settings/breakpoints.js, yarn.lock
This is using the https://github.com/ctrlplusb/react-component-queries , which in turn wraps https://github.com/wnr/element-resize-detector
=> Make Radio self responsive

Radio/index.js
=> Fix margin on one element Radio

Fieldset/index.jsx
=> Fix missing id in Fieldset fields

Field/example.jsx, Input/example.jsx, lib/features/inlinedIcon/index.jsx
=> Add location icon to Field and Input

.babelrc, Code/index.js, Code/syntaxes/index.js, IconButton/index.jsx, List/index.js, Selector/index.jsx, Showroom/Page/icons/index.js, Showroom/examples/components.js, Showroom/examples/compositions/index.jsx, Showroom/examples/index.js, Showroom/examples/templates.js, lib/features/inlinedIcon/index.jsx, package.json, templates/index.js, yarn.lock
Avoid using of stage-0 JS features
=> Remove direct export of imported dependencies

Checklist/example.jsx, Checklist/styles.scss
=> Fix Checklist positioning

Block/Bordered/styles.scss, Block/Installments/styles.scss, Block/example.jsx
=> Fix padding of block boxes

PromoLabel/example.js, PromoLabel/index.js, Showroom/examples/components.js
=> Add PromoLabel component

Field/example.jsx, FieldTooltip/index.jsx, FieldTooltip/styles.scss
Makes sure that the tooltip bubble stays visible when leaving the icon and entering the bubble itself.
=> Fix fieldtooltip hover

Radio/ExpandLabel/index.js, Radio/ExpandLabel/styles.js, Radio/Option/index.js, Radio/Option/styles.js, Radio/example.js, Radio/index.js, Radio/styles.js, RadioMark/example.jsx, RadioMark/index.js, RadioMark/styles.js
=> Add loading state to Radio

Dropdown/index.jsx
Tiny modification to the dropdown component.
=> Keep custom border radius for "disabled", "warning" and "error" states.

BoxSelector/Horizontal/index.jsx, BoxSelector/Horizontal/styles.scss, BoxSelector/Vertical/index.jsx, BoxSelector/Vertical/styles.scss, BoxSelector/example.jsx, BoxSelector/index.jsx
=> Add disabled status to options in BoxSelector

Field/index.jsx
Add option to customize the `border-shadow` when focused and also enhance the inline icon colouring.
=> Add more customization options to the Field component

Radio/Option/index.js, Radio/index.js
=> Adding onClick handler for disabled options in the Radio

Checklist/example.jsx, Checklist/index.jsx, Checklist/styles.scss
Add `bottomDecoration` to be able to show icons on the bottom border of `Checklist`
=> add bottomDecoration to Checklist
